# Generated by Django 4.2.6 on 2023-11-05 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('nua', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('foto', models.ImageField(null=True, upload_to='alumnos')),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('fecha', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jueves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semana_jueves', to='Academico.dia')),
                ('lunes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semana_lunes', to='Academico.dia')),
                ('martes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semana_martes', to='Academico.dia')),
                ('miercoles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semana_miercoles', to='Academico.dia')),
                ('viernes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semana_viernes', to='Academico.dia')),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.semana')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.CharField(max_length=3)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.alumno')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.dia')),
            ],
        ),
    ]
