# Generated by Django 4.2.6 on 2023-10-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_auto_20231028_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='foto',
            field=models.ImageField(null=True, upload_to='alumnos'),
        ),
    ]
